version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build: ./app
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db  
    environment:
      POSTGRES_USER: ${DB_USER}           
      POSTGRES_PASSWORD: ${DB_PASSWORD}   
      POSTGRES_DB: ${DB_NAME}             
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

volumes:
  pgdata:
