version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public/Fonts:/usr/share/nginx/html/fonts:ro  # Шрифты

    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
    depends_on:
      - backend

  backend:
    build: ./app
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      postgres: 
        condition: service_healthy

  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d my_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pg_data:
